[package]
name = "bento"
version = "0.1.0"
edition = "2021"
description = "A binary serialization libary"
license = "Apache-2.0"

[features]
default = ["derive"]
derive = ["dep:bento-derive"]

[dependencies]
bento-derive = { path = "../bento-derive", version = "=0.1.0", optional = true }
